version: "3.9"

services:
  db:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    command: >
      sh -c "python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py test --keepdb --parallel --shuffle &&
              python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SUPERUSER_PASSWORD=pass
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@ch3ck1n.com
      - ENV_NAME=dev
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432






